export function handleException(err: unknown): null {
  console.log(err);
  return null;
}
