export function handleException(err: any) {
  console.log(err);
  return null;
}
